### ISSUE TITLE
Can't build on windows

### ISSUE THREAD

**Issue by Riey** [RustPython/RustPython#1624]
```
   Compiling rustpython-parser v0.1.1 (https://github.com/RustPython/RustPython#a04c19cc)
   Compiling rustpython-compiler v0.1.1 (https://github.com/RustPython/RustPython#a04c19cc)
   Compiling rustpython-derive v0.1.1 (https://github.com/RustPython/RustPython#a04c19cc)
error: Compile error: Got unexpected token '.' at line 1 column 1
##[error]  --> C:\Users\runneradmin\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\a04c19c\vm\src\frozen.rs:21:18
   |
21 |     ext_modules!(dir = "Lib/python_builtins/");
   |     -------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^-- in this macro invocation

error: Compile error: Got unexpected token '.' at line 1 column 1
##[error]  --> C:\Users\runneradmin\.cargo\git\checkouts\rustpython-f8ef4d934ac33cd8\a04c19c\vm\src\frozen.rs:27:22
   |
27 |         ext_modules!(dir = "Lib/core_modules/");
   |         -------------^^^^^^^^^^^^^^^^^^^^^^^^^-- in this macro invocation

error: aborting due to 2 previous errors
##[error]aborting due to 2 previous errors
error: could not compile `rustpython-vm`.
##[error]could not compile `rustpython-vm`.
To learn more, run the command again with --verbose.
##[error]The process 'C:\Rust\.cargo\bin\cargo.exe' failed with exit code 101
##[error]Node run failed with exit code 1
```

**Comment by coolreader18** [comment]
Yeah, I thought this might be confusing. You can run `scripts/symlinks-to-hardlinks.ps1` to fix it.

**Comment by Riey** [comment]
@coolreader18 It looks like should be run to build  then why it doesn't included in build script?

**Comment by coolreader18** [comment]
That sounds like a good solution. It might not be great to have that be in the `rustpython-vm` script, since it might not be necessary when it's published on `crates.io`. @palaviv what do you think?

**Comment by coolreader18** [comment]
Oh, and this is from #1576; there's some discussion there already.

**Comment by palaviv** [comment]
> That sounds like a good solution. It might not be great to have that be in the `rustpython-vm` script, since it might not be necessary when it's published on `crates.io`. @palaviv what do you think?

That sounds good to me as long as it runs only on windows. My concern is our need to support this script. What versions of Powershell is the script supporting? Would this script work on all windows versions?

**Comment by windelbouwman** [comment]
Hmm, symlinks are troublesome without doubt. Is there a better way to solve this issue? Can we do without symlinks and powershell scripts? Maybe it makes sense to split off the frozen modules into a seperate crate? Does anyone have a good idea on how to approach this?

**Comment by IvanMoiseew** [comment]
**The error is repeated. Win7 64bit. Rust 1.40.0**

   Compiling rustpython-parser v0.1.1 (C:\Users\User\.rust_prog\py4\parser)
   Compiling rustpython-compiler v0.1.1 (C:\Users\User\.rust_prog\py4\compiler)
   Compiling rustpython-derive v0.1.1 (C:\Users\User\.rust_prog\py4\derive)
error[E0658]: procedural macros cannot expand to macro definitions
  --> vm\src\lib.rs:47:13
   |
47 |               $crate::_py_compile_bytecode!($($arg)*);
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
  ::: vm\src\frozen.rs:13:5
   |
13 | /     ext_modules!(
14 | |         source = "initialized = True; print(\"Hello world!\")\n",
15 | |         module_name = "__hello__",
16 | |     );
   | |______- in this macro invocation
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/54
727

error: Compile error: Got unexpected token '.' at line 1 column 1
  --> vm\src\frozen.rs:21:18
   |
21 |     ext_modules!(dir = "Lib/python_builtins/");
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Compile error: Got unexpected token '.' at line 1 column 1
  --> vm\src\frozen.rs:27:22
   |
27 |         ext_modules!(dir = "Lib/core_modules/");
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^

error: cannot find macro `__proc_macro_call!` in this scope
  --> vm\src\lib.rs:49:9
   |
49 |         __proc_macro_call!()
   |         ^^^^^^^^^^^^^^^^^
   |
  ::: vm\src\frozen.rs:21:5
   |
21 |     ext_modules!(dir = "Lib/python_builtins/");
   |     ------------------------------------------- in this macro invocation
   |
   = help: have you added the `#[macro_use]` on the module/import?

error: cannot find macro `__proc_macro_call!` in this scope
  --> vm\src\lib.rs:49:9
   |
49 |         __proc_macro_call!()
   |         ^^^^^^^^^^^^^^^^^
   |
  ::: vm\src\frozen.rs:27:9
   |
27 |         ext_modules!(dir = "Lib/core_modules/");
   |         ---------------------------------------- in this macro invocation
   |
   = help: have you added the `#[macro_use]` on the module/import?

error[E0658]: use of unstable library feature 'mem_take'
    --> vm\src\pyobject.rs:1222:1
     |
1222 | result_like::option_like!(pub PyArithmaticValue, Implemented, NotImplemen
ted);
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^
     |
     = note: for more information, see https://github.com/rust-lang/rust/issues/
61129
     = note: this error originates in a macro outside of the current crate (in N
ightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 6 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `rustpython-vm`.

To learn more, run the command again with --verbose.

**Comment by coolreader18** [comment]
Yeah, I'm working on the double error in the branch `coolreader18/improve-derive-diagnostics`. It still has the same solution as the single error, though.

**Comment by cedric-h** [comment]
Just ran into this.

**Comment by bcbqwe** [comment]
July 6, Ran "cargo run demo.py" on Windows 10 and got the same errors as above.
Ran powershell "scripts/symlinks-to-hardlinks.ps1" then "cargo run demo.py" again with the same result.

Is there a solution to this failure?

**Comment by coolreader18** [comment]
I'm really not sure, that Powershell script should fix it. Could you take a screenshot of the full output of running `powershell scripts/symlinks-to-hardlinks.ps1` and then `cargo run demo.py`?

**Comment by bcbqwe** [comment]
I am not experienced with powershell. I received no output from:

PS C:\RustPython\scripts> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
PS C:\RustPython\scripts> ./symlinks-to-hardlinks.ps1
PS C:\RustPython\scripts>

PS C:\RustPython> cargo run demo.py
   Compiling rustpython-vm v0.1.2 (C:\RustPython\vm)
error: Python compile error from Lib/python_builtins/_frozen_importlib.py: Got unexpected token '.' at line 1 column 1
  --> vm\src\frozen.rs:21:18
   |
21 |     ext_modules!(dir = "Lib/python_builtins/");
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: Python compile error from Lib/core_modules/copyreg.py: Got unexpected token '.' at line 1 column 1
  --> vm\src\frozen.rs:27:22
   |
27 |         ext_modules!(dir = "Lib/core_modules/");
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

error: could not compile `rustpython-vm`.

To learn more, run the command again with --verbose.
PS C:\RustPython>

**Comment by bcbqwe** [comment]
No solution though.

**Comment by cubewise-tryan** [comment]
Hi @bcbqwe,

Running `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser` and then `powershell scripts\symlinks-to-hardlinks.ps1` worked for me. Where you run the ps script from seems to be important, the script must use relative paths. Move one directory higher to the root and then run `powershell scripts\symlinks-to-hardlinks.ps1`.

**Comment by bcbqwe** [comment]
Thanks to cubewise-tryan. I successfully executed the commands but still received a compile error at the end:

PS C:\> git clone https://github.com/RustPython/RustPython
Cloning into 'RustPython'...
remote: Enumerating objects: 167, done.
remote: Counting objects: 100% (167/167), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 48840 (delta 62), reused 83 (delta 40), pack-reused 48673Receiving objects: 100% (48840/48840), 33.27 MiB Receiving objects: 100% (48840/48840), 35.92 MiB | 5.55 MiB/s, done.

Resolving deltas: 100% (38414/38414), done.
PS C:\> cd C:\RustPython
PS C:\RustPython> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\RustPython> scripts\symlinks-to-hardlinks.ps1


    Directory: C:\RustPython\vm\Lib\core_modules


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         9/30/2020  10:23 AM           7213 copyreg.py


    Directory: C:\RustPython\vm\Lib\python_builtins


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         9/30/2020  10:23 AM          41263 _frozen_importlib.py
-a----         9/30/2020  10:23 AM          63034 _frozen_importlib_external.py


    Directory: C:\RustPython\vm\pylib-crate


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----l         9/30/2020  10:24 AM                Lib


PS C:\RustPython> cargo run demo.py
   Compiling proc-macro2 v1.0.21
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.41
   Compiling autocfg v1.0.1
   Compiling winapi v0.3.9
   Compiling cfg-if v0.1.10
   Compiling serde_derive v1.0.116
multiple compiles ......................................................................
 Compiling rustpython-common v0.0.0 (C:\RustPython\common)
   Compiling num_enum_derive v0.4.3
   Compiling num_enum v0.4.3
   Compiling rustpython-parser v0.1.2 (C:\RustPython\parser)
   Compiling rustpython-compiler v0.1.2 (C:\RustPython\compiler)
   Compiling rustpython-derive v0.1.2 (C:\RustPython\derive)
error[E0658]: use of unstable library feature 'str_strip': newly added
   --> derive\src\pyclass.rs:562:46
    |
562 |                 if let Some(name) = sig_name.strip_prefix("set_") {
    |                                              ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information

error[E0658]: use of unstable library feature 'str_strip': newly added
   --> derive\src\pyclass.rs:651:58
    |
651 |             let name = if let Some(stripped) = ident_str.strip_prefix("tp_") {
    |                                                          ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information

error[E0658]: use of unstable library feature 'str_strip': newly added
   --> derive\src\pyclass.rs:764:36
    |
764 |             method_type: attr_name.strip_prefix("py").unwrap().to_owned(),
    |                                    ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `rustpython-derive`.

To learn more, run the command again with --verbose.
PS C:\RustPython>

**Comment by bcbqwe** [comment]
Thanks, 

 


I successfully executed the commands but still received a compile error at the end (different module this time). I add the log below as a comment to the closed #1624. Did I miss something?


 

 

PS C:> git clone  <https://github.com/RustPython/RustPython> https://github.com/RustPython/RustPython
Cloning into 'RustPython'...
remote: Enumerating objects: 167, done.
remote: Counting objects: 100% (167/167), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 48840 (delta 62), reused 83 (delta 40), pack-reused 48673Receiving objects: 100% (48840/48840), 33.27 MiB Receiving objects: 100% (48840/48840), 35.92 MiB | 5.55 MiB/s, done.

Resolving deltas: 100% (38414/38414), done.
PS C:> cd C:\RustPython
PS C:\RustPython> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes [A] Yes to All [N] No [L] No to All [S] Suspend [?] Help (default is "N"): Y
PS C:\RustPython> scripts\symlinks-to-hardlinks.ps1

Directory: C:\RustPython\vm\Lib\core_modules

Mode LastWriteTime Length Name

  _____  

-a---- 9/30/2020 10:23 AM 7213 copyreg.py

Directory: C:\RustPython\vm\Lib\python_builtins

Mode LastWriteTime Length Name

  _____  

-a---- 9/30/2020 10:23 AM 41263 _frozen_importlib.py
-a---- 9/30/2020 10:23 AM 63034 _frozen_importlib_external.py

Directory: C:\RustPython\vm\pylib-crate

Mode LastWriteTime Length Name

  _____  

d----l 9/30/2020 10:24 AM Lib

PS C:\RustPython> cargo run demo.py
Compiling proc-macro2 v1.0.21
Compiling unicode-xid v0.2.1
Compiling syn v1.0.41
Compiling autocfg v1.0.1
Compiling winapi v0.3.9
Compiling cfg-if v0.1.10
Compiling serde_derive v1.0.116
multiple compiles ......................................................................
Compiling rustpython-common v0.0.0 (C:\RustPython\common)
Compiling num_enum_derive v0.4.3
Compiling num_enum v0.4.3
Compiling rustpython-parser v0.1.2 (C:\RustPython\parser)
Compiling rustpython-compiler v0.1.2 (C:\RustPython\compiler)
Compiling rustpython-derive v0.1.2 (C:\RustPython\derive)
error[E0658]: use of unstable library feature 'str_strip': newly added
--> derive\src\pyclass.rs:562:46
|
562 | if let Some(name) = sig_name.strip_prefix("set_") {
| ^^^^^^^^^^^^
|
= note: see issue #67302  <https://github.com/rust-lang/rust/issues/67302> rust-lang/rust#67302 for more information

error[E0658]: use of unstable library feature 'str_strip': newly added
--> derive\src\pyclass.rs:651:58
|
651 | let name = if let Some(stripped) = ident_str.strip_prefix("tp_") {
| ^^^^^^^^^^^^
|
= note: see issue #67302  <https://github.com/rust-lang/rust/issues/67302> rust-lang/rust#67302 for more information

error[E0658]: use of unstable library feature 'str_strip': newly added
--> derive\src\pyclass.rs:764:36
|
764 | method_type: attr_name.strip_prefix("py").unwrap().to_owned(),
| ^^^^^^^^^^^^
|
= note: see issue #67302  <https://github.com/rust-lang/rust/issues/67302> rust-lang/rust#67302 for more information

error: aborting due to 3 previous errors

For more information about this error, try rustc --explain E0658.
error: could not compile rustpython-derive.

To learn more, run the command again with --verbose.
PS C:\RustPython>

**Comment by d00z3l** [comment]
Hi @bcbqwe,

Are you using rust stable or an old version of nightly? The error is saying that str_strip is an unstable feature. I think you need need update your rust version.

https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html

**Comment by coolreader18** [comment]
Yup @bcbqwe, try running `rustup update`, if you're using rustup. Otherwise, try re-installing rust in whatever method you originally did.

**Comment by coolreader18** [comment]
Try `cargo run --release demo.py`

**Comment by bcbqwe** [comment]
Success!  I ran:

cargo run --release demo.py

End of log:

 Compiling num_enum v0.4.3
   Compiling rustpython-parser v0.1.2 (C:\RustPython\parser)
   Compiling rustpython-compiler v0.1.2 (C:\RustPython\compiler)
   Compiling rustpython-derive v0.1.2 (C:\RustPython\derive)
   Compiling rustpython v0.1.2 (C:\RustPython)
    Finished release [optimized] target(s) in 4m 00s
     Running `target\release\rustpython.exe demo.py`
Hello, RustPython!
PS C:\RustPython>

**Comment by coolreader18** [comment]
I'll add some of these tips to the README, hopefully that would make it easier for windows users to get started

**Comment by mireille-raad** [comment]
@coolreader18 

<img width="634" alt="Screen Shot 2020-11-11 at 10 49 54 AM" src="https://user-images.githubusercontent.com/521705/98833187-bbdd1300-240b-11eb-99a7-91d402a26515.png">

is it safe to close this issue?
